version: '3'

services:
  client:
    build: ./client
    ports:
      - '3000:3000'
    volumes:
      - ./client:/usr/src/app
      - client_node_modules:/usr/src/app/node_modules
    env_file:
      - ./client/.env
  server:
    build: ./server
    ports:
      - '5000:5000'
    volumes:
      - ./server:/usr/src/app
      - server_node_modules:/usr/src/app/node_modules
    env_file:
      - ./server/.env

volumes:
  client_node_modules:
  server_node_modules:
